services:
  timescale:
    hostname: timescale
    image: timescale/timescaledb:2.17.2-pg17
    pull_policy: build
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - type: bind
        source: ./DDL.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
    environment:
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
    restart: always

  timescale-otsdb-adapter-api:
    image: timescale-otsdb-adapter-api
    build: .
    ports:
      - "8080:8080"
    environment:
      TIMESCALE_HOST: timescale
      TIMESCALE_PASSWORD: ${TIMESCALE_PASSWORD}
    restart: always

volumes:
  pgdata:
